create table imoveis(
    id bigint not null auto_increment,
    tipo_imovel varchar(50) not null,
    categoria varchar(50) not null,
    cep varchar(50) not null,
    logradouro varchar(50) not null,
    numero varchar(50) not null,
    complemento varchar(50),
    bairro varchar(50) not null,
    zona varchar(50),
    quartos int,
    banheiros int,
    suites float,
    vagas_garagem int,
    area_total float,
    area_util float,
    andares int,
    ano_construcao int,
    tipo_aquisicao varchar(50) not null,
    status_imovel varchar(50) not null,
    valor float not null,
    condominio float,
    iptu float,
    data_criacao datetime not null,
    descricao_opcional varchar(1000),
    documentacao_ok bit,
    ativo bit,

    primary key(id)
);